# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_sent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
