# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0005_auto_20170320_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('active', models.BooleanField()),
                ('template_name', models.CharField(max_length=20)),
            ],
        ),
    ]
