# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0007_auto_20170324_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingcampaign',
            old_name='active',
            new_name='import_done',
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
