# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0008_auto_20170324_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='smstext',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
