# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0009_auto_20170324_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingcampaign',
            old_name='url',
            new_name='import_url',
        ),
    ]
