# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0010_auto_20170324_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcampaign',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='retention.Client'),
        ),
    ]
