# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0011_auto_20170324_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcampaign',
            name='import_url',
        ),
        migrations.RemoveField(
            model_name='marketingcampaign',
            name='template_name',
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='import_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
