# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0012_auto_20170324_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingcampaign',
            old_name='import_file',
            new_name='customer_data',
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='subject_line',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
